### ISSUE TITLE
[Feature Request] Display in multiple bounding tiles at once

### ISSUE THREAD

**Issue by DaGwann** [mech-tools/share-media#46]
Simple feature to be able to select multiple bounding tiles when choosing where to display something with the "fit" or "cover" options.

Simple mock example:

![image](https://github.com/user-attachments/assets/494dd62f-c106-4653-9e88-787857cbf680)

**Comment by mech-tools** [comment]
Hi,

I don't have time right now to add any new features.
Still, I'm intrigued by the idea. What's your use case?

Also, I accept PR.

**Comment by DaGwann** [comment]
I have a landing page where I use your module to display different images (it's the background you can see on my image). I have added an option through active tiles so anyone can click on the area of the bounding tile and "zoom in" (the canvas pans to another section where the bounding tile occupies much more space in the canvas).

Right now, I have no problem in sending the image I want to display to each bounding tile individually one after the other, but it would be more convenient if I could select both at the same time.

Regardless if you find the time to add this feature or not, your module is a great addition and has made sharing media with my players so much more comfortable. Thank you! ^^

**Comment by mech-tools** [comment]
That was an easy one.
It has been released with: [1.1.0](https://github.com/mech-tools/share-media/releases/tag/1.1.0)
